services:
  xds-server:
    image: ghcr.io/cynicdog/xds-server-in-python:main
    ports:
      - "5678:5678"
    networks:
      - xds-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5678"]
      interval: 5s
      timeout: 2s
      retries: 10

  proxy:
    image: envoyproxy/envoy:v1.19.0
    ports:
      - "15000:15000"
      - "15001:15001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --service-cluster proxy -l warning
    networks:
      - xds-net
    depends_on:
      xds-server:
        condition: service_healthy

  httpbin:
    image: citizenstig/httpbin
    ports:
      - "8000:80"
    networks:
      - xds-net

networks:
  xds-net:
